import Head from 'next/head';

type Props = {
  children: React.ReactNode;
  title: string;
  description?: string;
};

const Layout: React.FC<Props> = ({ children, title, description }) => (
  <>
    <Head>
      <title>{title}</title>
      <meta
        name="description"
        content={description || 'Generated by create next app'}
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main sx={{ minHeight: '100vh' }}>{children}</main>
  </>
);

export default Layout;
